spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  jwt:
    secret: 12345678901234567890123456789012


profileImg.path:
      D:/intelliJ Project/profile_imgs/
    post.path:
      = D:/intelliJ Project/upload/
file:
  path: D:/city-hunter/src/main/resources/upload/

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

